run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configuring Git
        run: |
          git config --global user.name "re:Witless server"
          git config --global user.email "sunnext021999@gmail.com"
      
      - name: Installing main packages
        run: |
          if ! command -v yarn &> /dev/null
          then
            rm -rf $(npm list -g --depth=0 | head -1)/node_modules/yarn
            npm i -g yarn
          fi
          if ! command -v tsc &> /dev/null
          then
            rm -rf $(npm list -g --depth=0 | head -1)/node_modules/typescript
            npm i -g typescript
          fi
          
      #- name: Installing NodeJS
      #  run: |
      #    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      #    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      #    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      #    nvm install 16.13.0
      #    nvm use 16.13.0
          
      - name: Pulling changes
        run: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/witness
          cd ~/witness
          git fetch --all
          git reset --hard origin/main
          git clean -f -d
          git pull
      - name: Installing deps
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18.17.0
          cd ~/witness
          yarn
      - name: Compiling ts files
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18.17.0
          cd ~/witness && tsc
      - name: Creating temp folder
        run: cd ~/witness && mkdir -p temp
      - name: Restarting node process
        run: pm2 restart re:Witless
      
